### ISSUE TITLE
Bump client version

### ISSUE THREAD

**Issue by sebPomme** [ramnes/sftpgo-client#2]
Hi, thanks for this client :-) 

Can you bump the client version ?

Seem the api had some new features see  https://github.com/drakkan/sftpgo/commit/23d9ebfc91ae9414a5672ab9e7dab47766b320b2 .
Personally, I need the new `HTTP` protocol `sftpgo_client.base.models.supported_protocols.SupportedProtocols`.

Thanks

**Comment by ramnes** [comment]
Done and released. Ça fera 100 € merci. <3

If you need to update it again in the future, please look at the README and open a PR, I've written how to run the generator.
